### ISSUE TITLE
library hangs at disableWatchdog() if example code in README is used

### ISSUE THREAD

**Issue by hraftery** [cyrusbuilt/SAMCrashMonitor#10]
The example in the README calls `SAMCrashMonitor::disableWatchdog();` early on. If this is used as given in an otherwise bare Arduino SAMD21 project, the program will hang at this point.

The issue appears to be that `while (WDT->STATUS.bit.SYNCBUSY);` never returns.

The workaround appears to be to call `SAMCrashMonitor::begin();` first.

**Comment by cyrusbuilt** [comment]
Updated readme.
