### ISSUE TITLE
Is it possible to include a user-specified callback similar to what's in the ArduinoCrashMonitor?

### ISSUE THREAD

**Issue by caiello3** [cyrusbuilt/SAMCrashMonitor#7]
Since the SAM D21 does not have an EEPROM to write the crash info to, would it be possible to include a user-specified callback function similar to what you have built in the original ArduinoCrashMonitor?

What I'd hope to do is use an SD card attached to the board and write the crash data to that, eliminating the dependency on the serial monitor to read the crash data.

**Comment by cyrusbuilt** [comment]
The short answer is: 'yes'.  But.... there is a caveat: Once a condition is met that will cause a reset to occur, there is no stopping or delaying that reset from occurring.  Sort of.  What I mean is, the way this library works is it hooks into what Atmel calls 'an early warning interrupt'.  Which is an interrupt that fires just before the interrupt that triggers the reset.  I *CAN* add the ability to add a callback that fires when that EWI fires, but I will caution that your code needs to be a short as possible and even then might not execute fast enough to complete before the reset occurs.  The SAM is much more aggressive with its interrupts than the AVRs.  My concern would be that the amount of time needed to access and store the crash report on external SD card storage would be too long.  But we can certainly give it a try and see what happens.

**Comment by cyrusbuilt** [comment]
Ok try the code in this branch: [https://github.com/cyrusbuilt/SAMCrashMonitor.git#UserCrashHandler](https://github.com/cyrusbuilt/SAMCrashMonitor.git#UserCrashHandler).  After reviewing the code again, it doesn't use an EWI for hard-faults. It only uses and EWI for Watchdog interrupts.  So to set a callback for handling hard faults, you would do so like this:

```cpp
void MyHandler(SAMCrashReport &report) {
    // Do something with the report.
}

SAMCrashMonitor::setUserCrashHandler(MyHandler);
```

This callback *only* gets called on a hard fault. NOT on a watchdog reset.  A watchdog reset isn't really a fault per se.  It just means the watch dog wasn't fed before the timeout.  Besides, I can only capture crash reports with the interrupt for a hard fault triggers.  That being said, this SHOULD give you what you are looking for.  Give it a shot and let me know.  To trigger a hard fault, do a divide-by-zero sometime after you set the handler
